# Generated by Django 4.2.1 on 2023-06-04 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_id', models.CharField(max_length=30)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('customer', models.CharField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=10000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('workflow_config', models.CharField(blank=True, null=True)),
                ('service_category', models.CharField(blank=True, null=True)),
                ('impact_service', models.CharField(blank=True, null=True)),
                ('service_classification', models.CharField(blank=True, null=True)),
                ('state', models.CharField(blank=True, null=True)),
                ('status', models.CharField(blank=True, null=True)),
                ('impact', models.SmallIntegerField(default=1)),
                ('urgency', models.SmallIntegerField(default=1)),
                ('priority', models.SmallIntegerField(default=1)),
                ('group', models.CharField(blank=True, null=True)),
                ('level', models.CharField(blank=True, null=True)),
                ('source', models.SmallIntegerField(default=1)),
                ('resolution_type', models.CharField(max_length=30)),
                ('resolutionTime', models.CharField(max_length=30)),
                ('symptom', models.TextField()),
                ('root_cause', models.TextField()),
                ('resolution', models.TextField()),
                ('trouble_reason', models.TextField()),
                ('recovery_action', models.TextField()),
                ('closure_note', models.TextField()),
                ('closed_type', models.CharField(max_length=30)),
                ('agreed_closure_date', models.DateTimeField(null=True)),
                ('actual_closure_date', models.DateTimeField(null=True)),
                ('person_name', models.CharField(blank=True, max_length=255, null=True)),
                ('person_email', models.TextField(blank=True, null=True)),
                ('person_phone', models.TextField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_assignee', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_closed_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
