# Generated by Django 4.2.1 on 2023-06-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='actual_closure_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='agreed_closure_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='closed_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='closure_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='recovery_action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='resolution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='resolutionTime',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='resolution_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='root_cause',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='symptom',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='trouble_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
