# Generated by Django 4.2.1 on 2023-06-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
