# Generated by Django 4.2.1 on 2023-06-07 13:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_remove_userprofile_contact_extension_requester'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requester',
            new_name='Customer',
        ),
    ]
