# Generated by Django 4.2.1 on 2023-06-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_alter_state_name_alter_workflow_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
