# Generated by Django 4.2.1 on 2023-06-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_alter_status_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='stage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
