# Generated by Django 4.2.1 on 2023-06-18 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_state_wf_status_state_status_wf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_stage_rule', models.BooleanField(default=False)),
                ('if_stage', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('if_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='if_state', to='workflow.state')),
                ('if_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='if_status', to='workflow.status')),
                ('then_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='then_state', to='workflow.state')),
                ('then_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='then_status', to='workflow.status')),
                ('wf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.workflow')),
            ],
            options={
                'db_table': 'tbl_rules',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stage', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(max_length=1000)),
                ('body', models.TextField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.state')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.status')),
                ('wf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.workflow')),
            ],
            options={
                'db_table': 'tbl_notifications',
            },
        ),
    ]
