# Generated by Django 4.2.1 on 2023-06-18 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_rules_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='if_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='if_state', to='workflow.state'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='if_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='if_status', to='workflow.status'),
        ),
    ]
