# Generated by Django 4.2.1 on 2023-06-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_alter_rules_if_state_alter_rules_if_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='is_stage_notification',
            field=models.BooleanField(default=False),
        ),
    ]
