# Generated by Django 4.2.1 on 2023-06-19 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_notifications_is_stage_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.state'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.status'),
        ),
    ]
